require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InterviewSlotsController do

  # This should return the minimal set of attributes required to create a valid
  # InterviewSlot. As you add validations to InterviewSlot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InterviewSlotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all interview_slots as @interview_slots" do
      interview_slot = InterviewSlot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interview_slots).should eq([interview_slot])
    end
  end

  describe "GET show" do
    it "assigns the requested interview_slot as @interview_slot" do
      interview_slot = InterviewSlot.create! valid_attributes
      get :show, {:id => interview_slot.to_param}, valid_session
      assigns(:interview_slot).should eq(interview_slot)
    end
  end

  describe "GET new" do
    it "assigns a new interview_slot as @interview_slot" do
      get :new, {}, valid_session
      assigns(:interview_slot).should be_a_new(InterviewSlot)
    end
  end

  describe "GET edit" do
    it "assigns the requested interview_slot as @interview_slot" do
      interview_slot = InterviewSlot.create! valid_attributes
      get :edit, {:id => interview_slot.to_param}, valid_session
      assigns(:interview_slot).should eq(interview_slot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InterviewSlot" do
        expect {
          post :create, {:interview_slot => valid_attributes}, valid_session
        }.to change(InterviewSlot, :count).by(1)
      end

      it "assigns a newly created interview_slot as @interview_slot" do
        post :create, {:interview_slot => valid_attributes}, valid_session
        assigns(:interview_slot).should be_a(InterviewSlot)
        assigns(:interview_slot).should be_persisted
      end

      it "redirects to the created interview_slot" do
        post :create, {:interview_slot => valid_attributes}, valid_session
        response.should redirect_to(InterviewSlot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interview_slot as @interview_slot" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterviewSlot.any_instance.stub(:save).and_return(false)
        post :create, {:interview_slot => {  }}, valid_session
        assigns(:interview_slot).should be_a_new(InterviewSlot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterviewSlot.any_instance.stub(:save).and_return(false)
        post :create, {:interview_slot => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interview_slot" do
        interview_slot = InterviewSlot.create! valid_attributes
        # Assuming there are no other interview_slots in the database, this
        # specifies that the InterviewSlot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InterviewSlot.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => interview_slot.to_param, :interview_slot => { "these" => "params" }}, valid_session
      end

      it "assigns the requested interview_slot as @interview_slot" do
        interview_slot = InterviewSlot.create! valid_attributes
        put :update, {:id => interview_slot.to_param, :interview_slot => valid_attributes}, valid_session
        assigns(:interview_slot).should eq(interview_slot)
      end

      it "redirects to the interview_slot" do
        interview_slot = InterviewSlot.create! valid_attributes
        put :update, {:id => interview_slot.to_param, :interview_slot => valid_attributes}, valid_session
        response.should redirect_to(interview_slot)
      end
    end

    describe "with invalid params" do
      it "assigns the interview_slot as @interview_slot" do
        interview_slot = InterviewSlot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterviewSlot.any_instance.stub(:save).and_return(false)
        put :update, {:id => interview_slot.to_param, :interview_slot => {  }}, valid_session
        assigns(:interview_slot).should eq(interview_slot)
      end

      it "re-renders the 'edit' template" do
        interview_slot = InterviewSlot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterviewSlot.any_instance.stub(:save).and_return(false)
        put :update, {:id => interview_slot.to_param, :interview_slot => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interview_slot" do
      interview_slot = InterviewSlot.create! valid_attributes
      expect {
        delete :destroy, {:id => interview_slot.to_param}, valid_session
      }.to change(InterviewSlot, :count).by(-1)
    end

    it "redirects to the interview_slots list" do
      interview_slot = InterviewSlot.create! valid_attributes
      delete :destroy, {:id => interview_slot.to_param}, valid_session
      response.should redirect_to(interview_slots_url)
    end
  end

end
